name: ammeba-etl

volumes:
  ammeba:

services:
  extract-data:
    container_name: etl_extract_ammeba
    image: python:3.11
    user: root
    volumes:
      - ./data:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e

        echo "Resetting directory..."
        rm -rf final_dataset
        mkdir -p final_dataset
        cd final_dataset

        echo "Downloading final_dataset.zip..."
        curl -L https://nyu.box.com/shared/static/liey7cih8kgori1hon6ussg4dx76wvjd.zip \
          -o final_dataset.zip

        echo "Unzipping..."
        unzip -q final_dataset.zip
        rm final_dataset.zip

        echo "Dataset content:"
        find /data/final_dataset -type f | head -n 10

  load-data:
    container_name: etl_load_ammeba
    image: rclone/rclone:latest
    volumes:
      - ./data:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        echo "Cleaning up existing contents in object-persist-project-5 ..."
        rclone delete chi_tacc:object-persist-project-5 --rmdirs || true

        echo "Uploading final_dataset/ to object store..."
        rclone copy /data/final_dataset chi_tacc:object-persist-project-5 \
          --progress \
          --transfers=32 \
          --checkers=16 \
          --multi-thread-streams=4 \
          --fast-list

        echo "Verifying structure:"
        rclone tree chi_tacc:object-persist-project-5 --max-depth 2
