FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel

USER ${NB_UID}

# 设置工作目录
WORKDIR /workspace

# 安装系统工具
RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# 安装 Python 包
RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
        jupyter \
        notebook \
        jupyterlab \
        ipywidgets \
        matplotlib \
        pandas \
        mlflow \
        pynvml

# 设置 Jupyter Notebook 的默认启动命令
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
