FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel

# Set the working directory
WORKDIR /workspace

# Install system tools
RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
        jupyter \
        notebook \
        jupyterlab \
        ipywidgets \
        matplotlib \
        pandas \
        mlflow \
        pynvml

# Set the default startup command for Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
